spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update #create 최초 1회
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true #ture 최초 1회
        show_sql: true

  logging:
      level:
        com.tutorial: debug

  jwt:
    header: Authorization
    secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

omdb:
  api:
    key: 29d33c7c